/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Album = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'description' : IDL.Opt(IDL.Text),
  'artist' : IDL.Text,
  'coverPath' : IDL.Opt(IDL.Text),
  'releaseYear' : IDL.Opt(IDL.Text),
});
export const FeatureCard = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'icon' : IDL.Text,
  'color' : IDL.Text,
  'subtitle' : IDL.Text,
});
export const MediaItem = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'trackNumber' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'albumCoverPath' : IDL.Opt(IDL.Text),
  'thumbnailPath' : IDL.Opt(IDL.Text),
  'waveformPath' : IDL.Opt(IDL.Text),
  'albumId' : IDL.Opt(IDL.Text),
  'mediaType' : IDL.Text,
  'isAlbumTrack' : IDL.Bool,
  'albumTitle' : IDL.Opt(IDL.Text),
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'inventory' : IDL.Nat,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'isDigital' : IDL.Bool,
});
export const StudioService = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'imagePath' : IDL.Opt(IDL.Text),
  'order' : IDL.Nat,
  'description' : IDL.Text,
  'mediaSamples' : IDL.Vec(IDL.Text),
  'price' : IDL.Text,
});
export const StudioStat = IDL.Record({
  'id' : IDL.Text,
  'order' : IDL.Nat,
  'icon' : IDL.Text,
  'statLabel' : IDL.Text,
});
export const TeachingModel = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'features' : IDL.Vec(IDL.Text),
  'imagePath' : IDL.Opt(IDL.Text),
  'order' : IDL.Nat,
  'description' : IDL.Text,
  'price' : IDL.Text,
  'subtitle' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const AboutSection = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const AnimationConfig = IDL.Record({
  'animationDuration' : IDL.Nat,
  'scrollAnimationsEnabled' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ColorScheme = IDL.Record({
  'backgroundColor' : IDL.Text,
  'primaryColor' : IDL.Text,
  'gradientEnabled' : IDL.Bool,
  'gradientEndColor' : IDL.Text,
  'secondaryColor' : IDL.Text,
  'gradientStartColor' : IDL.Text,
  'textColor' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
});
export const FileReference = IDL.Record({
  'hash' : IDL.Text,
  'path' : IDL.Text,
});
export const HeaderSection = IDL.Record({
  'verticalPadding' : IDL.Nat,
  'logoPath' : IDL.Text,
  'compact' : IDL.Bool,
  'logoSizePercent' : IDL.Nat,
});
export const HeroSection = IDL.Record({
  'backgroundImageUrl' : IDL.Opt(IDL.Text),
  'headline' : IDL.Text,
  'ctaSecondary' : IDL.Text,
  'subheadline' : IDL.Text,
  'ctaPrimary' : IDL.Text,
});
export const LegalDocument = IDL.Record({
  'content' : IDL.Text,
  'lastUpdated' : IDL.Nat64,
});
export const LandingPageConfig = IDL.Record({
  'featuredContentType' : IDL.Text,
  'featuredContentId' : IDL.Opt(IDL.Nat),
  'showFeaturedContent' : IDL.Bool,
});
export const SiteTexts = IDL.Record({
  'unterrichtHeadline' : IDL.Opt(IDL.Text),
  'shopIntro' : IDL.Opt(IDL.Text),
  'studioCTA' : IDL.Opt(IDL.Text),
  'mediaCTA' : IDL.Opt(IDL.Text),
  'shopCTA' : IDL.Opt(IDL.Text),
  'studioIntro' : IDL.Opt(IDL.Text),
  'unterrichtIntro' : IDL.Opt(IDL.Text),
  'mediaIntro' : IDL.Opt(IDL.Text),
  'unterrichtCTA' : IDL.Opt(IDL.Text),
  'shopHeadline' : IDL.Opt(IDL.Text),
  'footerCopyright' : IDL.Opt(IDL.Text),
  'mediaHeadline' : IDL.Opt(IDL.Text),
  'studioHeadline' : IDL.Opt(IDL.Text),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const AdminCredentials = IDL.Record({
  'username' : IDL.Text,
  'passwordHash' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addAlbum' : IDL.Func([Album], [], []),
  'addFeatureCard' : IDL.Func([FeatureCard], [IDL.Nat], []),
  'addMediaItem' : IDL.Func([MediaItem], [IDL.Nat], []),
  'addProduct' : IDL.Func([Product], [IDL.Nat], []),
  'addStudioService' : IDL.Func([StudioService], [IDL.Nat], []),
  'addStudioStat' : IDL.Func([StudioStat], [], []),
  'addTeachingModel' : IDL.Func([TeachingModel], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteAlbum' : IDL.Func([IDL.Text], [], []),
  'deleteFeatureCard' : IDL.Func([IDL.Nat], [], []),
  'deleteMediaItem' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'deleteStudioService' : IDL.Func([IDL.Nat], [], []),
  'deleteStudioStat' : IDL.Func([IDL.Text], [], []),
  'deleteTeachingModel' : IDL.Func([IDL.Nat], [], []),
  'dropFileReference' : IDL.Func([IDL.Text], [], []),
  'getAboutSection' : IDL.Func([], [AboutSection], ['query']),
  'getAlbums' : IDL.Func([], [IDL.Vec(Album)], ['query']),
  'getAnimationConfig' : IDL.Func([], [AnimationConfig], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getColorScheme' : IDL.Func([], [ColorScheme], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getFaviconUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getFeatureCards' : IDL.Func([], [IDL.Vec(FeatureCard)], ['query']),
  'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
  'getHeaderSection' : IDL.Func([], [HeaderSection], ['query']),
  'getHeroSection' : IDL.Func([], [HeroSection], ['query']),
  'getImprint' : IDL.Func([], [LegalDocument], ['query']),
  'getLandingPageConfig' : IDL.Func([], [LandingPageConfig], ['query']),
  'getLogoSizePercent' : IDL.Func([], [IDL.Nat], ['query']),
  'getMediaItems' : IDL.Func([], [IDL.Vec(MediaItem)], ['query']),
  'getPrivacyPolicy' : IDL.Func([], [LegalDocument], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getSiteLogoUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getSiteTexts' : IDL.Func([], [SiteTexts], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getStudioServices' : IDL.Func([], [IDL.Vec(StudioService)], ['query']),
  'getStudioStats' : IDL.Func([], [IDL.Vec(StudioStat)], ['query']),
  'getTeachingModels' : IDL.Func([], [IDL.Vec(TeachingModel)], ['query']),
  'getTermsOfService' : IDL.Func([], [LegalDocument], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
  'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'resetAdminForNewPrincipal' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAboutSection' : IDL.Func([AboutSection], [], []),
  'updateAdminCredentials' : IDL.Func([AdminCredentials], [], []),
  'updateAdminSetupCode' : IDL.Func([IDL.Text], [], []),
  'updateAlbum' : IDL.Func([Album], [], []),
  'updateAnimationConfig' : IDL.Func([AnimationConfig], [], []),
  'updateColorScheme' : IDL.Func([ColorScheme], [], []),
  'updateContactInfo' : IDL.Func([ContactInfo], [], []),
  'updateFaviconUrl' : IDL.Func([IDL.Text], [], []),
  'updateFeatureCard' : IDL.Func([FeatureCard], [], []),
  'updateHeroSection' : IDL.Func([HeroSection], [], []),
  'updateImprint' : IDL.Func([IDL.Text], [], []),
  'updateLandingPageConfig' : IDL.Func([LandingPageConfig], [], []),
  'updateLogoSizePercent' : IDL.Func([IDL.Nat], [], []),
  'updateMediaItem' : IDL.Func([MediaItem], [], []),
  'updatePrivacyPolicy' : IDL.Func([IDL.Text], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'updateSiteLogoUrl' : IDL.Func([IDL.Text], [], []),
  'updateSiteTexts' : IDL.Func([SiteTexts], [], []),
  'updateStudioService' : IDL.Func([StudioService], [], []),
  'updateStudioStat' : IDL.Func([StudioStat], [], []),
  'updateTeachingModel' : IDL.Func([TeachingModel], [], []),
  'updateTermsOfService' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Album = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'description' : IDL.Opt(IDL.Text),
    'artist' : IDL.Text,
    'coverPath' : IDL.Opt(IDL.Text),
    'releaseYear' : IDL.Opt(IDL.Text),
  });
  const FeatureCard = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'icon' : IDL.Text,
    'color' : IDL.Text,
    'subtitle' : IDL.Text,
  });
  const MediaItem = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'trackNumber' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'albumCoverPath' : IDL.Opt(IDL.Text),
    'thumbnailPath' : IDL.Opt(IDL.Text),
    'waveformPath' : IDL.Opt(IDL.Text),
    'albumId' : IDL.Opt(IDL.Text),
    'mediaType' : IDL.Text,
    'isAlbumTrack' : IDL.Bool,
    'albumTitle' : IDL.Opt(IDL.Text),
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'inventory' : IDL.Nat,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'isDigital' : IDL.Bool,
  });
  const StudioService = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'imagePath' : IDL.Opt(IDL.Text),
    'order' : IDL.Nat,
    'description' : IDL.Text,
    'mediaSamples' : IDL.Vec(IDL.Text),
    'price' : IDL.Text,
  });
  const StudioStat = IDL.Record({
    'id' : IDL.Text,
    'order' : IDL.Nat,
    'icon' : IDL.Text,
    'statLabel' : IDL.Text,
  });
  const TeachingModel = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'features' : IDL.Vec(IDL.Text),
    'imagePath' : IDL.Opt(IDL.Text),
    'order' : IDL.Nat,
    'description' : IDL.Text,
    'price' : IDL.Text,
    'subtitle' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const AboutSection = IDL.Record({ 'title' : IDL.Text, 'content' : IDL.Text });
  const AnimationConfig = IDL.Record({
    'animationDuration' : IDL.Nat,
    'scrollAnimationsEnabled' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ColorScheme = IDL.Record({
    'backgroundColor' : IDL.Text,
    'primaryColor' : IDL.Text,
    'gradientEnabled' : IDL.Bool,
    'gradientEndColor' : IDL.Text,
    'secondaryColor' : IDL.Text,
    'gradientStartColor' : IDL.Text,
    'textColor' : IDL.Text,
  });
  const ContactInfo = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Opt(IDL.Text),
  });
  const FileReference = IDL.Record({ 'hash' : IDL.Text, 'path' : IDL.Text });
  const HeaderSection = IDL.Record({
    'verticalPadding' : IDL.Nat,
    'logoPath' : IDL.Text,
    'compact' : IDL.Bool,
    'logoSizePercent' : IDL.Nat,
  });
  const HeroSection = IDL.Record({
    'backgroundImageUrl' : IDL.Opt(IDL.Text),
    'headline' : IDL.Text,
    'ctaSecondary' : IDL.Text,
    'subheadline' : IDL.Text,
    'ctaPrimary' : IDL.Text,
  });
  const LegalDocument = IDL.Record({
    'content' : IDL.Text,
    'lastUpdated' : IDL.Nat64,
  });
  const LandingPageConfig = IDL.Record({
    'featuredContentType' : IDL.Text,
    'featuredContentId' : IDL.Opt(IDL.Nat),
    'showFeaturedContent' : IDL.Bool,
  });
  const SiteTexts = IDL.Record({
    'unterrichtHeadline' : IDL.Opt(IDL.Text),
    'shopIntro' : IDL.Opt(IDL.Text),
    'studioCTA' : IDL.Opt(IDL.Text),
    'mediaCTA' : IDL.Opt(IDL.Text),
    'shopCTA' : IDL.Opt(IDL.Text),
    'studioIntro' : IDL.Opt(IDL.Text),
    'unterrichtIntro' : IDL.Opt(IDL.Text),
    'mediaIntro' : IDL.Opt(IDL.Text),
    'unterrichtCTA' : IDL.Opt(IDL.Text),
    'shopHeadline' : IDL.Opt(IDL.Text),
    'footerCopyright' : IDL.Opt(IDL.Text),
    'mediaHeadline' : IDL.Opt(IDL.Text),
    'studioHeadline' : IDL.Opt(IDL.Text),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const AdminCredentials = IDL.Record({
    'username' : IDL.Text,
    'passwordHash' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addAlbum' : IDL.Func([Album], [], []),
    'addFeatureCard' : IDL.Func([FeatureCard], [IDL.Nat], []),
    'addMediaItem' : IDL.Func([MediaItem], [IDL.Nat], []),
    'addProduct' : IDL.Func([Product], [IDL.Nat], []),
    'addStudioService' : IDL.Func([StudioService], [IDL.Nat], []),
    'addStudioStat' : IDL.Func([StudioStat], [], []),
    'addTeachingModel' : IDL.Func([TeachingModel], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteAlbum' : IDL.Func([IDL.Text], [], []),
    'deleteFeatureCard' : IDL.Func([IDL.Nat], [], []),
    'deleteMediaItem' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'deleteStudioService' : IDL.Func([IDL.Nat], [], []),
    'deleteStudioStat' : IDL.Func([IDL.Text], [], []),
    'deleteTeachingModel' : IDL.Func([IDL.Nat], [], []),
    'dropFileReference' : IDL.Func([IDL.Text], [], []),
    'getAboutSection' : IDL.Func([], [AboutSection], ['query']),
    'getAlbums' : IDL.Func([], [IDL.Vec(Album)], ['query']),
    'getAnimationConfig' : IDL.Func([], [AnimationConfig], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getColorScheme' : IDL.Func([], [ColorScheme], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getFaviconUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getFeatureCards' : IDL.Func([], [IDL.Vec(FeatureCard)], ['query']),
    'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
    'getHeaderSection' : IDL.Func([], [HeaderSection], ['query']),
    'getHeroSection' : IDL.Func([], [HeroSection], ['query']),
    'getImprint' : IDL.Func([], [LegalDocument], ['query']),
    'getLandingPageConfig' : IDL.Func([], [LandingPageConfig], ['query']),
    'getLogoSizePercent' : IDL.Func([], [IDL.Nat], ['query']),
    'getMediaItems' : IDL.Func([], [IDL.Vec(MediaItem)], ['query']),
    'getPrivacyPolicy' : IDL.Func([], [LegalDocument], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getSiteLogoUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getSiteTexts' : IDL.Func([], [SiteTexts], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getStudioServices' : IDL.Func([], [IDL.Vec(StudioService)], ['query']),
    'getStudioStats' : IDL.Func([], [IDL.Vec(StudioStat)], ['query']),
    'getTeachingModels' : IDL.Func([], [IDL.Vec(TeachingModel)], ['query']),
    'getTermsOfService' : IDL.Func([], [LegalDocument], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
    'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'resetAdminForNewPrincipal' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAboutSection' : IDL.Func([AboutSection], [], []),
    'updateAdminCredentials' : IDL.Func([AdminCredentials], [], []),
    'updateAdminSetupCode' : IDL.Func([IDL.Text], [], []),
    'updateAlbum' : IDL.Func([Album], [], []),
    'updateAnimationConfig' : IDL.Func([AnimationConfig], [], []),
    'updateColorScheme' : IDL.Func([ColorScheme], [], []),
    'updateContactInfo' : IDL.Func([ContactInfo], [], []),
    'updateFaviconUrl' : IDL.Func([IDL.Text], [], []),
    'updateFeatureCard' : IDL.Func([FeatureCard], [], []),
    'updateHeroSection' : IDL.Func([HeroSection], [], []),
    'updateImprint' : IDL.Func([IDL.Text], [], []),
    'updateLandingPageConfig' : IDL.Func([LandingPageConfig], [], []),
    'updateLogoSizePercent' : IDL.Func([IDL.Nat], [], []),
    'updateMediaItem' : IDL.Func([MediaItem], [], []),
    'updatePrivacyPolicy' : IDL.Func([IDL.Text], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'updateSiteLogoUrl' : IDL.Func([IDL.Text], [], []),
    'updateSiteTexts' : IDL.Func([SiteTexts], [], []),
    'updateStudioService' : IDL.Func([StudioService], [], []),
    'updateStudioStat' : IDL.Func([StudioStat], [], []),
    'updateTeachingModel' : IDL.Func([TeachingModel], [], []),
    'updateTermsOfService' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };