/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutSection { 'title' : string, 'content' : string }
export interface AdminCredentials {
  'username' : string,
  'passwordHash' : string,
}
export interface Album {
  'id' : string,
  'title' : string,
  'order' : bigint,
  'description' : [] | [string],
  'artist' : string,
  'coverPath' : [] | [string],
  'releaseYear' : [] | [string],
}
export interface AnimationConfig {
  'animationDuration' : bigint,
  'scrollAnimationsEnabled' : boolean,
}
export interface ColorScheme {
  'backgroundColor' : string,
  'primaryColor' : string,
  'gradientEnabled' : boolean,
  'gradientEndColor' : string,
  'secondaryColor' : string,
  'gradientStartColor' : string,
  'textColor' : string,
}
export interface ContactInfo {
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : [] | [string],
}
export interface FeatureCard {
  'id' : bigint,
  'title' : string,
  'order' : bigint,
  'icon' : string,
  'color' : string,
  'subtitle' : string,
}
export interface FileReference { 'hash' : string, 'path' : string }
export interface HeaderSection {
  'verticalPadding' : bigint,
  'logoPath' : string,
  'compact' : boolean,
  'logoSizePercent' : bigint,
}
export interface HeroSection {
  'backgroundImageUrl' : [] | [string],
  'headline' : string,
  'ctaSecondary' : string,
  'subheadline' : string,
  'ctaPrimary' : string,
}
export interface LandingPageConfig {
  'featuredContentType' : string,
  'featuredContentId' : [] | [bigint],
  'showFeaturedContent' : boolean,
}
export interface LegalDocument { 'content' : string, 'lastUpdated' : bigint }
export interface MediaItem {
  'id' : bigint,
  'url' : string,
  'title' : string,
  'trackNumber' : [] | [bigint],
  'description' : string,
  'albumCoverPath' : [] | [string],
  'thumbnailPath' : [] | [string],
  'waveformPath' : [] | [string],
  'albumId' : [] | [string],
  'mediaType' : string,
  'isAlbumTrack' : boolean,
  'albumTitle' : [] | [string],
}
export interface Product {
  'id' : bigint,
  'title' : string,
  'inventory' : bigint,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
  'isDigital' : boolean,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SiteTexts {
  'unterrichtHeadline' : [] | [string],
  'shopIntro' : [] | [string],
  'studioCTA' : [] | [string],
  'mediaCTA' : [] | [string],
  'shopCTA' : [] | [string],
  'studioIntro' : [] | [string],
  'unterrichtIntro' : [] | [string],
  'mediaIntro' : [] | [string],
  'unterrichtCTA' : [] | [string],
  'shopHeadline' : [] | [string],
  'footerCopyright' : [] | [string],
  'mediaHeadline' : [] | [string],
  'studioHeadline' : [] | [string],
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface StudioService {
  'id' : bigint,
  'title' : string,
  'imagePath' : [] | [string],
  'order' : bigint,
  'description' : string,
  'mediaSamples' : Array<string>,
  'price' : string,
}
export interface StudioStat {
  'id' : string,
  'order' : bigint,
  'icon' : string,
  'statLabel' : string,
}
export interface TeachingModel {
  'id' : bigint,
  'title' : string,
  'featured' : boolean,
  'features' : Array<string>,
  'imagePath' : [] | [string],
  'order' : bigint,
  'description' : string,
  'price' : string,
  'subtitle' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<string>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<string>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addAlbum' : ActorMethod<[Album], undefined>,
  'addFeatureCard' : ActorMethod<[FeatureCard], bigint>,
  'addMediaItem' : ActorMethod<[MediaItem], bigint>,
  'addProduct' : ActorMethod<[Product], bigint>,
  'addStudioService' : ActorMethod<[StudioService], bigint>,
  'addStudioStat' : ActorMethod<[StudioStat], undefined>,
  'addTeachingModel' : ActorMethod<[TeachingModel], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteAlbum' : ActorMethod<[string], undefined>,
  'deleteFeatureCard' : ActorMethod<[bigint], undefined>,
  'deleteMediaItem' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deleteStudioService' : ActorMethod<[bigint], undefined>,
  'deleteStudioStat' : ActorMethod<[string], undefined>,
  'deleteTeachingModel' : ActorMethod<[bigint], undefined>,
  'dropFileReference' : ActorMethod<[string], undefined>,
  'getAboutSection' : ActorMethod<[], AboutSection>,
  'getAlbums' : ActorMethod<[], Array<Album>>,
  'getAnimationConfig' : ActorMethod<[], AnimationConfig>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getColorScheme' : ActorMethod<[], ColorScheme>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'getFaviconUrl' : ActorMethod<[], string>,
  'getFeatureCards' : ActorMethod<[], Array<FeatureCard>>,
  'getFileReference' : ActorMethod<[string], FileReference>,
  'getHeaderSection' : ActorMethod<[], HeaderSection>,
  'getHeroSection' : ActorMethod<[], HeroSection>,
  'getImprint' : ActorMethod<[], LegalDocument>,
  'getLandingPageConfig' : ActorMethod<[], LandingPageConfig>,
  'getLogoSizePercent' : ActorMethod<[], bigint>,
  'getMediaItems' : ActorMethod<[], Array<MediaItem>>,
  'getPrivacyPolicy' : ActorMethod<[], LegalDocument>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getSiteLogoUrl' : ActorMethod<[], string>,
  'getSiteTexts' : ActorMethod<[], SiteTexts>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getStudioServices' : ActorMethod<[], Array<StudioService>>,
  'getStudioStats' : ActorMethod<[], Array<StudioStat>>,
  'getTeachingModels' : ActorMethod<[], Array<TeachingModel>>,
  'getTermsOfService' : ActorMethod<[], LegalDocument>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listFileReferences' : ActorMethod<[], Array<FileReference>>,
  'registerFileReference' : ActorMethod<[string, string], undefined>,
  'resetAdminForNewPrincipal' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAboutSection' : ActorMethod<[AboutSection], undefined>,
  'updateAdminCredentials' : ActorMethod<[AdminCredentials], undefined>,
  'updateAdminSetupCode' : ActorMethod<[string], undefined>,
  'updateAlbum' : ActorMethod<[Album], undefined>,
  'updateAnimationConfig' : ActorMethod<[AnimationConfig], undefined>,
  'updateColorScheme' : ActorMethod<[ColorScheme], undefined>,
  'updateContactInfo' : ActorMethod<[ContactInfo], undefined>,
  'updateFaviconUrl' : ActorMethod<[string], undefined>,
  'updateFeatureCard' : ActorMethod<[FeatureCard], undefined>,
  'updateHeroSection' : ActorMethod<[HeroSection], undefined>,
  'updateImprint' : ActorMethod<[string], undefined>,
  'updateLandingPageConfig' : ActorMethod<[LandingPageConfig], undefined>,
  'updateLogoSizePercent' : ActorMethod<[bigint], undefined>,
  'updateMediaItem' : ActorMethod<[MediaItem], undefined>,
  'updatePrivacyPolicy' : ActorMethod<[string], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updateSiteLogoUrl' : ActorMethod<[string], undefined>,
  'updateSiteTexts' : ActorMethod<[SiteTexts], undefined>,
  'updateStudioService' : ActorMethod<[StudioService], undefined>,
  'updateStudioStat' : ActorMethod<[StudioStat], undefined>,
  'updateTeachingModel' : ActorMethod<[TeachingModel], undefined>,
  'updateTermsOfService' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];