/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface MediaItem {
    id: bigint;
    url: string;
    title: string;
    trackNumber?: bigint;
    description: string;
    albumCoverPath?: string;
    thumbnailPath?: string;
    waveformPath?: string;
    albumId?: string;
    mediaType: string;
    isAlbumTrack: boolean;
    albumTitle?: string;
}
export interface HeroSection {
    backgroundImageUrl?: string;
    headline: string;
    ctaSecondary: string;
    subheadline: string;
    ctaPrimary: string;
}
export interface LandingPageConfig {
    featuredContentType: string;
    featuredContentId?: bigint;
    showFeaturedContent: boolean;
}
export interface Album {
    id: string;
    title: string;
    order: bigint;
    description?: string;
    artist: string;
    coverPath?: string;
    releaseYear?: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface ColorScheme {
    backgroundColor: string;
    primaryColor: string;
    gradientEnabled: boolean;
    gradientEndColor: string;
    secondaryColor: string;
    gradientStartColor: string;
    textColor: string;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface FileReference {
    hash: string;
    path: string;
}
export interface ContactInfo {
    name: string;
    email: string;
    address: string;
    phone?: string;
}
export interface AdminCredentials {
    username: string;
    passwordHash: string;
}
export interface TeachingModel {
    id: bigint;
    title: string;
    featured: boolean;
    features: Array<string>;
    imagePath?: string;
    order: bigint;
    description: string;
    price: string;
    subtitle: string;
}
export interface SiteTexts {
    unterrichtHeadline?: string;
    shopIntro?: string;
    studioCTA?: string;
    mediaCTA?: string;
    shopCTA?: string;
    studioIntro?: string;
    unterrichtIntro?: string;
    mediaIntro?: string;
    unterrichtCTA?: string;
    shopHeadline?: string;
    footerCopyright?: string;
    mediaHeadline?: string;
    studioHeadline?: string;
}
export interface AboutSection {
    title: string;
    content: string;
}
export interface StudioService {
    id: bigint;
    title: string;
    imagePath?: string;
    order: bigint;
    description: string;
    mediaSamples: Array<string>;
    price: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface StudioStat {
    id: string;
    order: bigint;
    icon: string;
    statLabel: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface LegalDocument {
    content: string;
    lastUpdated: bigint;
}
export interface HeaderSection {
    verticalPadding: bigint;
    logoPath: string;
    compact: boolean;
    logoSizePercent: bigint;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface AnimationConfig {
    animationDuration: bigint;
    scrollAnimationsEnabled: boolean;
}
export interface FeatureCard {
    id: bigint;
    title: string;
    order: bigint;
    icon: string;
    color: string;
    subtitle: string;
}
export interface Product {
    id: bigint;
    title: string;
    inventory: bigint;
    description: string;
    imageUrl: string;
    category: string;
    price: bigint;
    isDigital: boolean;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobsToDelete(): Promise<Array<string>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<string>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addAlbum(album: Album): Promise<void>;
    addFeatureCard(card: FeatureCard): Promise<bigint>;
    addMediaItem(item: MediaItem): Promise<bigint>;
    addProduct(product: Product): Promise<bigint>;
    addStudioService(service: StudioService): Promise<bigint>;
    addStudioStat(stat: StudioStat): Promise<void>;
    addTeachingModel(model: TeachingModel): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    deleteAlbum(id: string): Promise<void>;
    deleteFeatureCard(id: bigint): Promise<void>;
    deleteMediaItem(id: bigint): Promise<void>;
    deleteProduct(id: bigint): Promise<void>;
    deleteStudioService(id: bigint): Promise<void>;
    deleteStudioStat(id: string): Promise<void>;
    deleteTeachingModel(id: bigint): Promise<void>;
    dropFileReference(path: string): Promise<void>;
    getAboutSection(): Promise<AboutSection>;
    getAlbums(): Promise<Array<Album>>;
    getAnimationConfig(): Promise<AnimationConfig>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getColorScheme(): Promise<ColorScheme>;
    getContactInfo(): Promise<ContactInfo>;
    getFaviconUrl(): Promise<string>;
    getFeatureCards(): Promise<Array<FeatureCard>>;
    getFileReference(path: string): Promise<FileReference>;
    getHeaderSection(): Promise<HeaderSection>;
    getHeroSection(): Promise<HeroSection>;
    getImprint(): Promise<LegalDocument>;
    getLandingPageConfig(): Promise<LandingPageConfig>;
    getLogoSizePercent(): Promise<bigint>;
    getMediaItems(): Promise<Array<MediaItem>>;
    getPrivacyPolicy(): Promise<LegalDocument>;
    getProducts(): Promise<Array<Product>>;
    getSiteLogoUrl(): Promise<string>;
    getSiteTexts(): Promise<SiteTexts>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getStudioServices(): Promise<Array<StudioService>>;
    getStudioStats(): Promise<Array<StudioStat>>;
    getTeachingModels(): Promise<Array<TeachingModel>>;
    getTermsOfService(): Promise<LegalDocument>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listFileReferences(): Promise<Array<FileReference>>;
    registerFileReference(path: string, hash: string): Promise<void>;
    resetAdminForNewPrincipal(setupCode: string): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAboutSection(section: AboutSection): Promise<void>;
    updateAdminCredentials(newCredentials: AdminCredentials): Promise<void>;
    updateAdminSetupCode(newCode: string): Promise<void>;
    updateAlbum(album: Album): Promise<void>;
    updateAnimationConfig(config: AnimationConfig): Promise<void>;
    updateColorScheme(newScheme: ColorScheme): Promise<void>;
    updateContactInfo(info: ContactInfo): Promise<void>;
    updateFaviconUrl(url: string): Promise<void>;
    updateFeatureCard(card: FeatureCard): Promise<void>;
    updateHeroSection(section: HeroSection): Promise<void>;
    updateImprint(content: string): Promise<void>;
    updateLandingPageConfig(config: LandingPageConfig): Promise<void>;
    updateLogoSizePercent(size: bigint): Promise<void>;
    updateMediaItem(item: MediaItem): Promise<void>;
    updatePrivacyPolicy(content: string): Promise<void>;
    updateProduct(product: Product): Promise<void>;
    updateSiteLogoUrl(url: string): Promise<void>;
    updateSiteTexts(updated: SiteTexts): Promise<void>;
    updateStudioService(service: StudioService): Promise<void>;
    updateStudioStat(stat: StudioStat): Promise<void>;
    updateTeachingModel(model: TeachingModel): Promise<void>;
    updateTermsOfService(content: string): Promise<void>;
}
import type { Album as _Album, ContactInfo as _ContactInfo, HeroSection as _HeroSection, LandingPageConfig as _LandingPageConfig, MediaItem as _MediaItem, SiteTexts as _SiteTexts, StripeSessionStatus as _StripeSessionStatus, StudioService as _StudioService, TeachingModel as _TeachingModel, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobsToDelete(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addAlbum(arg0: Album): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAlbum(to_candid_Album_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAlbum(to_candid_Album_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addFeatureCard(arg0: FeatureCard): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addFeatureCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFeatureCard(arg0);
            return result;
        }
    }
    async addMediaItem(arg0: MediaItem): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMediaItem(to_candid_MediaItem_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMediaItem(to_candid_MediaItem_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addProduct(arg0: Product): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0);
            return result;
        }
    }
    async addStudioService(arg0: StudioService): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudioService(to_candid_StudioService_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudioService(to_candid_StudioService_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addStudioStat(arg0: StudioStat): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudioStat(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudioStat(arg0);
            return result;
        }
    }
    async addTeachingModel(arg0: TeachingModel): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeachingModel(to_candid_TeachingModel_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeachingModel(to_candid_TeachingModel_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteAlbum(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAlbum(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAlbum(arg0);
            return result;
        }
    }
    async deleteFeatureCard(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFeatureCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFeatureCard(arg0);
            return result;
        }
    }
    async deleteMediaItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMediaItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMediaItem(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteStudioService(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudioService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudioService(arg0);
            return result;
        }
    }
    async deleteStudioStat(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudioStat(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudioStat(arg0);
            return result;
        }
    }
    async deleteTeachingModel(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeachingModel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeachingModel(arg0);
            return result;
        }
    }
    async dropFileReference(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dropFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dropFileReference(arg0);
            return result;
        }
    }
    async getAboutSection(): Promise<AboutSection> {
        if (this.processError) {
            try {
                const result = await this.actor.getAboutSection();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAboutSection();
            return result;
        }
    }
    async getAlbums(): Promise<Array<Album>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlbums();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlbums();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnimationConfig(): Promise<AnimationConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnimationConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnimationConfig();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getColorScheme(): Promise<ColorScheme> {
        if (this.processError) {
            try {
                const result = await this.actor.getColorScheme();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getColorScheme();
            return result;
        }
    }
    async getContactInfo(): Promise<ContactInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactInfo();
                return from_candid_ContactInfo_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactInfo();
            return from_candid_ContactInfo_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFaviconUrl(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getFaviconUrl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFaviconUrl();
            return result;
        }
    }
    async getFeatureCards(): Promise<Array<FeatureCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeatureCards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeatureCards();
            return result;
        }
    }
    async getFileReference(arg0: string): Promise<FileReference> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileReference(arg0);
            return result;
        }
    }
    async getHeaderSection(): Promise<HeaderSection> {
        if (this.processError) {
            try {
                const result = await this.actor.getHeaderSection();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHeaderSection();
            return result;
        }
    }
    async getHeroSection(): Promise<HeroSection> {
        if (this.processError) {
            try {
                const result = await this.actor.getHeroSection();
                return from_candid_HeroSection_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHeroSection();
            return from_candid_HeroSection_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getImprint(): Promise<LegalDocument> {
        if (this.processError) {
            try {
                const result = await this.actor.getImprint();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImprint();
            return result;
        }
    }
    async getLandingPageConfig(): Promise<LandingPageConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getLandingPageConfig();
                return from_candid_LandingPageConfig_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLandingPageConfig();
            return from_candid_LandingPageConfig_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLogoSizePercent(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogoSizePercent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogoSizePercent();
            return result;
        }
    }
    async getMediaItems(): Promise<Array<MediaItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMediaItems();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMediaItems();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrivacyPolicy(): Promise<LegalDocument> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrivacyPolicy();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrivacyPolicy();
            return result;
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return result;
        }
    }
    async getSiteLogoUrl(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteLogoUrl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteLogoUrl();
            return result;
        }
    }
    async getSiteTexts(): Promise<SiteTexts> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteTexts();
                return from_candid_SiteTexts_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteTexts();
            return from_candid_SiteTexts_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudioServices(): Promise<Array<StudioService>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudioServices();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudioServices();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudioStats(): Promise<Array<StudioStat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudioStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudioStats();
            return result;
        }
    }
    async getTeachingModels(): Promise<Array<TeachingModel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeachingModels();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeachingModels();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTermsOfService(): Promise<LegalDocument> {
        if (this.processError) {
            try {
                const result = await this.actor.getTermsOfService();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTermsOfService();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listFileReferences(): Promise<Array<FileReference>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFileReferences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFileReferences();
            return result;
        }
    }
    async registerFileReference(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerFileReference(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerFileReference(arg0, arg1);
            return result;
        }
    }
    async resetAdminForNewPrincipal(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAdminForNewPrincipal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAdminForNewPrincipal(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAboutSection(arg0: AboutSection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAboutSection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAboutSection(arg0);
            return result;
        }
    }
    async updateAdminCredentials(arg0: AdminCredentials): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminCredentials(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminCredentials(arg0);
            return result;
        }
    }
    async updateAdminSetupCode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminSetupCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminSetupCode(arg0);
            return result;
        }
    }
    async updateAlbum(arg0: Album): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAlbum(to_candid_Album_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAlbum(to_candid_Album_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAnimationConfig(arg0: AnimationConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnimationConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnimationConfig(arg0);
            return result;
        }
    }
    async updateColorScheme(arg0: ColorScheme): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateColorScheme(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateColorScheme(arg0);
            return result;
        }
    }
    async updateContactInfo(arg0: ContactInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContactInfo(to_candid_ContactInfo_n45(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContactInfo(to_candid_ContactInfo_n45(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateFaviconUrl(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFaviconUrl(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFaviconUrl(arg0);
            return result;
        }
    }
    async updateFeatureCard(arg0: FeatureCard): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFeatureCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFeatureCard(arg0);
            return result;
        }
    }
    async updateHeroSection(arg0: HeroSection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHeroSection(to_candid_HeroSection_n47(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHeroSection(to_candid_HeroSection_n47(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateImprint(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateImprint(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateImprint(arg0);
            return result;
        }
    }
    async updateLandingPageConfig(arg0: LandingPageConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLandingPageConfig(to_candid_LandingPageConfig_n49(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLandingPageConfig(to_candid_LandingPageConfig_n49(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateLogoSizePercent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLogoSizePercent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLogoSizePercent(arg0);
            return result;
        }
    }
    async updateMediaItem(arg0: MediaItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMediaItem(to_candid_MediaItem_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMediaItem(to_candid_MediaItem_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updatePrivacyPolicy(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePrivacyPolicy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePrivacyPolicy(arg0);
            return result;
        }
    }
    async updateProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0);
            return result;
        }
    }
    async updateSiteLogoUrl(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSiteLogoUrl(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSiteLogoUrl(arg0);
            return result;
        }
    }
    async updateSiteTexts(arg0: SiteTexts): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSiteTexts(to_candid_SiteTexts_n51(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSiteTexts(to_candid_SiteTexts_n51(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateStudioService(arg0: StudioService): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudioService(to_candid_StudioService_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudioService(to_candid_StudioService_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateStudioStat(arg0: StudioStat): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudioStat(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudioStat(arg0);
            return result;
        }
    }
    async updateTeachingModel(arg0: TeachingModel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeachingModel(to_candid_TeachingModel_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeachingModel(to_candid_TeachingModel_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTermsOfService(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTermsOfService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTermsOfService(arg0);
            return result;
        }
    }
}
function from_candid_Album_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Album): Album {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_ContactInfo_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactInfo): ContactInfo {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_HeroSection_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HeroSection): HeroSection {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_LandingPageConfig_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LandingPageConfig): LandingPageConfig {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_MediaItem_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaItem): MediaItem {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_SiteTexts_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SiteTexts): SiteTexts {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_StudioService_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudioService): StudioService {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_TeachingModel_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeachingModel): TeachingModel {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    order: bigint;
    description: [] | [string];
    artist: string;
    coverPath: [] | [string];
    releaseYear: [] | [string];
}): {
    id: string;
    title: string;
    order: bigint;
    description?: string;
    artist: string;
    coverPath?: string;
    releaseYear?: string;
} {
    return {
        id: value.id,
        title: value.title,
        order: value.order,
        description: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.description)),
        artist: value.artist,
        coverPath: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.coverPath)),
        releaseYear: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.releaseYear))
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    address: string;
    phone: [] | [string];
}): {
    name: string;
    email: string;
    address: string;
    phone?: string;
} {
    return {
        name: value.name,
        email: value.email,
        address: value.address,
        phone: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    backgroundImageUrl: [] | [string];
    headline: string;
    ctaSecondary: string;
    subheadline: string;
    ctaPrimary: string;
}): {
    backgroundImageUrl?: string;
    headline: string;
    ctaSecondary: string;
    subheadline: string;
    ctaPrimary: string;
} {
    return {
        backgroundImageUrl: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.backgroundImageUrl)),
        headline: value.headline,
        ctaSecondary: value.ctaSecondary,
        subheadline: value.subheadline,
        ctaPrimary: value.ctaPrimary
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    featuredContentType: string;
    featuredContentId: [] | [bigint];
    showFeaturedContent: boolean;
}): {
    featuredContentType: string;
    featuredContentId?: bigint;
    showFeaturedContent: boolean;
} {
    return {
        featuredContentType: value.featuredContentType,
        featuredContentId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.featuredContentId)),
        showFeaturedContent: value.showFeaturedContent
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    url: string;
    title: string;
    trackNumber: [] | [bigint];
    description: string;
    albumCoverPath: [] | [string];
    thumbnailPath: [] | [string];
    waveformPath: [] | [string];
    albumId: [] | [string];
    mediaType: string;
    isAlbumTrack: boolean;
    albumTitle: [] | [string];
}): {
    id: bigint;
    url: string;
    title: string;
    trackNumber?: bigint;
    description: string;
    albumCoverPath?: string;
    thumbnailPath?: string;
    waveformPath?: string;
    albumId?: string;
    mediaType: string;
    isAlbumTrack: boolean;
    albumTitle?: string;
} {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        trackNumber: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.trackNumber)),
        description: value.description,
        albumCoverPath: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.albumCoverPath)),
        thumbnailPath: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.thumbnailPath)),
        waveformPath: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.waveformPath)),
        albumId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.albumId)),
        mediaType: value.mediaType,
        isAlbumTrack: value.isAlbumTrack,
        albumTitle: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.albumTitle))
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unterrichtHeadline: [] | [string];
    shopIntro: [] | [string];
    studioCTA: [] | [string];
    mediaCTA: [] | [string];
    shopCTA: [] | [string];
    studioIntro: [] | [string];
    unterrichtIntro: [] | [string];
    mediaIntro: [] | [string];
    unterrichtCTA: [] | [string];
    shopHeadline: [] | [string];
    footerCopyright: [] | [string];
    mediaHeadline: [] | [string];
    studioHeadline: [] | [string];
}): {
    unterrichtHeadline?: string;
    shopIntro?: string;
    studioCTA?: string;
    mediaCTA?: string;
    shopCTA?: string;
    studioIntro?: string;
    unterrichtIntro?: string;
    mediaIntro?: string;
    unterrichtCTA?: string;
    shopHeadline?: string;
    footerCopyright?: string;
    mediaHeadline?: string;
    studioHeadline?: string;
} {
    return {
        unterrichtHeadline: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.unterrichtHeadline)),
        shopIntro: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.shopIntro)),
        studioCTA: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.studioCTA)),
        mediaCTA: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.mediaCTA)),
        shopCTA: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.shopCTA)),
        studioIntro: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.studioIntro)),
        unterrichtIntro: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.unterrichtIntro)),
        mediaIntro: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.mediaIntro)),
        unterrichtCTA: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.unterrichtCTA)),
        shopHeadline: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.shopHeadline)),
        footerCopyright: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.footerCopyright)),
        mediaHeadline: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.mediaHeadline)),
        studioHeadline: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.studioHeadline))
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    imagePath: [] | [string];
    order: bigint;
    description: string;
    mediaSamples: Array<string>;
    price: string;
}): {
    id: bigint;
    title: string;
    imagePath?: string;
    order: bigint;
    description: string;
    mediaSamples: Array<string>;
    price: string;
} {
    return {
        id: value.id,
        title: value.title,
        imagePath: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.imagePath)),
        order: value.order,
        description: value.description,
        mediaSamples: value.mediaSamples,
        price: value.price
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    featured: boolean;
    features: Array<string>;
    imagePath: [] | [string];
    order: bigint;
    description: string;
    price: string;
    subtitle: string;
}): {
    id: bigint;
    title: string;
    featured: boolean;
    features: Array<string>;
    imagePath?: string;
    order: bigint;
    description: string;
    price: string;
    subtitle: string;
} {
    return {
        id: value.id,
        title: value.title,
        featured: value.featured,
        features: value.features,
        imagePath: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.imagePath)),
        order: value.order,
        description: value.description,
        price: value.price,
        subtitle: value.subtitle
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n38(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Album>): Array<Album> {
    return value.map((x)=>from_candid_Album_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MediaItem>): Array<MediaItem> {
    return value.map((x)=>from_candid_MediaItem_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudioService>): Array<StudioService> {
    return value.map((x)=>from_candid_StudioService_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TeachingModel>): Array<TeachingModel> {
    return value.map((x)=>from_candid_TeachingModel_n43(_uploadFile, _downloadFile, x));
}
function to_candid_Album_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Album): _Album {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ContactInfo_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContactInfo): _ContactInfo {
    return to_candid_record_n46(_uploadFile, _downloadFile, value);
}
function to_candid_HeroSection_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HeroSection): _HeroSection {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_LandingPageConfig_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LandingPageConfig): _LandingPageConfig {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_MediaItem_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaItem): _MediaItem {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_SiteTexts_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SiteTexts): _SiteTexts {
    return to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid_StudioService_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudioService): _StudioService {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_TeachingModel_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeachingModel): _TeachingModel {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    url: string;
    title: string;
    trackNumber?: bigint;
    description: string;
    albumCoverPath?: string;
    thumbnailPath?: string;
    waveformPath?: string;
    albumId?: string;
    mediaType: string;
    isAlbumTrack: boolean;
    albumTitle?: string;
}): {
    id: bigint;
    url: string;
    title: string;
    trackNumber: [] | [bigint];
    description: string;
    albumCoverPath: [] | [string];
    thumbnailPath: [] | [string];
    waveformPath: [] | [string];
    albumId: [] | [string];
    mediaType: string;
    isAlbumTrack: boolean;
    albumTitle: [] | [string];
} {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        trackNumber: value.trackNumber ? candid_some(value.trackNumber) : candid_none(),
        description: value.description,
        albumCoverPath: value.albumCoverPath ? candid_some(value.albumCoverPath) : candid_none(),
        thumbnailPath: value.thumbnailPath ? candid_some(value.thumbnailPath) : candid_none(),
        waveformPath: value.waveformPath ? candid_some(value.waveformPath) : candid_none(),
        albumId: value.albumId ? candid_some(value.albumId) : candid_none(),
        mediaType: value.mediaType,
        isAlbumTrack: value.isAlbumTrack,
        albumTitle: value.albumTitle ? candid_some(value.albumTitle) : candid_none()
    };
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    imagePath?: string;
    order: bigint;
    description: string;
    mediaSamples: Array<string>;
    price: string;
}): {
    id: bigint;
    title: string;
    imagePath: [] | [string];
    order: bigint;
    description: string;
    mediaSamples: Array<string>;
    price: string;
} {
    return {
        id: value.id,
        title: value.title,
        imagePath: value.imagePath ? candid_some(value.imagePath) : candid_none(),
        order: value.order,
        description: value.description,
        mediaSamples: value.mediaSamples,
        price: value.price
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    featured: boolean;
    features: Array<string>;
    imagePath?: string;
    order: bigint;
    description: string;
    price: string;
    subtitle: string;
}): {
    id: bigint;
    title: string;
    featured: boolean;
    features: Array<string>;
    imagePath: [] | [string];
    order: bigint;
    description: string;
    price: string;
    subtitle: string;
} {
    return {
        id: value.id,
        title: value.title,
        featured: value.featured,
        features: value.features,
        imagePath: value.imagePath ? candid_some(value.imagePath) : candid_none(),
        order: value.order,
        description: value.description,
        price: value.price,
        subtitle: value.subtitle
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    address: string;
    phone?: string;
}): {
    name: string;
    email: string;
    address: string;
    phone: [] | [string];
} {
    return {
        name: value.name,
        email: value.email,
        address: value.address,
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    backgroundImageUrl?: string;
    headline: string;
    ctaSecondary: string;
    subheadline: string;
    ctaPrimary: string;
}): {
    backgroundImageUrl: [] | [string];
    headline: string;
    ctaSecondary: string;
    subheadline: string;
    ctaPrimary: string;
} {
    return {
        backgroundImageUrl: value.backgroundImageUrl ? candid_some(value.backgroundImageUrl) : candid_none(),
        headline: value.headline,
        ctaSecondary: value.ctaSecondary,
        subheadline: value.subheadline,
        ctaPrimary: value.ctaPrimary
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    featuredContentType: string;
    featuredContentId?: bigint;
    showFeaturedContent: boolean;
}): {
    featuredContentType: string;
    featuredContentId: [] | [bigint];
    showFeaturedContent: boolean;
} {
    return {
        featuredContentType: value.featuredContentType,
        featuredContentId: value.featuredContentId ? candid_some(value.featuredContentId) : candid_none(),
        showFeaturedContent: value.showFeaturedContent
    };
}
function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unterrichtHeadline?: string;
    shopIntro?: string;
    studioCTA?: string;
    mediaCTA?: string;
    shopCTA?: string;
    studioIntro?: string;
    unterrichtIntro?: string;
    mediaIntro?: string;
    unterrichtCTA?: string;
    shopHeadline?: string;
    footerCopyright?: string;
    mediaHeadline?: string;
    studioHeadline?: string;
}): {
    unterrichtHeadline: [] | [string];
    shopIntro: [] | [string];
    studioCTA: [] | [string];
    mediaCTA: [] | [string];
    shopCTA: [] | [string];
    studioIntro: [] | [string];
    unterrichtIntro: [] | [string];
    mediaIntro: [] | [string];
    unterrichtCTA: [] | [string];
    shopHeadline: [] | [string];
    footerCopyright: [] | [string];
    mediaHeadline: [] | [string];
    studioHeadline: [] | [string];
} {
    return {
        unterrichtHeadline: value.unterrichtHeadline ? candid_some(value.unterrichtHeadline) : candid_none(),
        shopIntro: value.shopIntro ? candid_some(value.shopIntro) : candid_none(),
        studioCTA: value.studioCTA ? candid_some(value.studioCTA) : candid_none(),
        mediaCTA: value.mediaCTA ? candid_some(value.mediaCTA) : candid_none(),
        shopCTA: value.shopCTA ? candid_some(value.shopCTA) : candid_none(),
        studioIntro: value.studioIntro ? candid_some(value.studioIntro) : candid_none(),
        unterrichtIntro: value.unterrichtIntro ? candid_some(value.unterrichtIntro) : candid_none(),
        mediaIntro: value.mediaIntro ? candid_some(value.mediaIntro) : candid_none(),
        unterrichtCTA: value.unterrichtCTA ? candid_some(value.unterrichtCTA) : candid_none(),
        shopHeadline: value.shopHeadline ? candid_some(value.shopHeadline) : candid_none(),
        footerCopyright: value.footerCopyright ? candid_some(value.footerCopyright) : candid_none(),
        mediaHeadline: value.mediaHeadline ? candid_some(value.mediaHeadline) : candid_none(),
        studioHeadline: value.studioHeadline ? candid_some(value.studioHeadline) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    order: bigint;
    description?: string;
    artist: string;
    coverPath?: string;
    releaseYear?: string;
}): {
    id: string;
    title: string;
    order: bigint;
    description: [] | [string];
    artist: string;
    coverPath: [] | [string];
    releaseYear: [] | [string];
} {
    return {
        id: value.id,
        title: value.title,
        order: value.order,
        description: value.description ? candid_some(value.description) : candid_none(),
        artist: value.artist,
        coverPath: value.coverPath ? candid_some(value.coverPath) : candid_none(),
        releaseYear: value.releaseYear ? candid_some(value.releaseYear) : candid_none()
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
